#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateAddressAction {
    /// Determines the kind of action.
    #[prost(enumeration = "UpdateAction", tag = "1")]
    pub action: i32,
    /// The address used to apply the update action.
    #[prost(string, tag = "2")]
    pub address: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateFeatureAction {
    /// Determines the kind of action.
    #[prost(enumeration = "UpdateAction", tag = "1")]
    pub action: i32,
    /// The feature bit used to apply the update action.
    #[prost(enumeration = "super::lnrpc::FeatureBit", tag = "2")]
    pub feature_bit: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeAnnouncementUpdateRequest {
    /// Set of changes for the features that the node supports.
    #[prost(message, repeated, tag = "1")]
    pub feature_updates: ::prost::alloc::vec::Vec<UpdateFeatureAction>,
    /// Color is the node's color in hex code format.
    #[prost(string, tag = "2")]
    pub color: ::prost::alloc::string::String,
    /// Alias or nick name of the node.
    #[prost(string, tag = "3")]
    pub alias: ::prost::alloc::string::String,
    /// Set of changes for the node's known addresses.
    #[prost(message, repeated, tag = "4")]
    pub address_updates: ::prost::alloc::vec::Vec<UpdateAddressAction>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeAnnouncementUpdateResponse {
    #[prost(message, repeated, tag = "1")]
    pub ops: ::prost::alloc::vec::Vec<super::lnrpc::Op>,
}
/// UpdateAction is used to determine the kind of action we are referring to.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UpdateAction {
    /// ADD indicates this is an "insertion" kind of action.
    Add = 0,
    /// REMOVE indicates this is a "deletion" kind of action.
    Remove = 1,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FeatureSet {
    ///
    ///SET_INIT identifies features that should be sent in an Init message to
    ///a remote peer.
    SetInit = 0,
    ///
    ///SET_LEGACY_GLOBAL identifies features that should be set in the legacy
    ///GlobalFeatures field of an Init message, which maintains backwards
    ///compatibility with nodes that haven't implemented flat features.
    SetLegacyGlobal = 1,
    ///
    ///SET_NODE_ANN identifies features that should be advertised on node
    ///announcements.
    SetNodeAnn = 2,
    ///
    ///SET_INVOICE identifies features that should be advertised on invoices
    ///generated by the daemon.
    SetInvoice = 3,
    ///
    ///SET_INVOICE_AMP identifies the features that should be advertised on
    ///AMP invoices generated by the daemon.
    SetInvoiceAmp = 4,
}
#[doc = r" Generated client implementations."]
pub mod peers_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    #[doc = " Peers is a service that can be used to get information and interact"]
    #[doc = " with the other nodes of the newtwork."]
    #[derive(Debug, Clone)]
    pub struct PeersClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl PeersClient<tonic::transport::Channel> {
        #[doc = r" Attempt to create a new client by connecting to a given endpoint."]
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: std::convert::TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> PeersClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::ResponseBody: Body + Send + 'static,
        T::Error: Into<StdError>,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> PeersClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<http::Request<tonic::body::BoxBody>>>::Error:
                Into<StdError> + Send + Sync,
        {
            PeersClient::new(InterceptedService::new(inner, interceptor))
        }
        #[doc = r" Compress requests with `gzip`."]
        #[doc = r""]
        #[doc = r" This requires the server to support it otherwise it might respond with an"]
        #[doc = r" error."]
        pub fn send_gzip(mut self) -> Self {
            self.inner = self.inner.send_gzip();
            self
        }
        #[doc = r" Enable decompressing responses with `gzip`."]
        pub fn accept_gzip(mut self) -> Self {
            self.inner = self.inner.accept_gzip();
            self
        }
        #[doc = " lncli: peers updatenodeannouncement"]
        #[doc = "UpdateNodeAnnouncement allows the caller to update the node parameters"]
        #[doc = "and broadcasts a new version of the node announcement to its peers."]
        pub async fn update_node_announcement(
            &mut self,
            request: impl tonic::IntoRequest<super::NodeAnnouncementUpdateRequest>,
        ) -> Result<tonic::Response<super::NodeAnnouncementUpdateResponse>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/peersrpc.Peers/UpdateNodeAnnouncement");
            self.inner.unary(request.into_request(), path, codec).await
        }
    }
}
#[doc = r" Generated server implementations."]
pub mod peers_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    #[doc = "Generated trait containing gRPC methods that should be implemented for use with PeersServer."]
    #[async_trait]
    pub trait Peers: Send + Sync + 'static {
        #[doc = " lncli: peers updatenodeannouncement"]
        #[doc = "UpdateNodeAnnouncement allows the caller to update the node parameters"]
        #[doc = "and broadcasts a new version of the node announcement to its peers."]
        async fn update_node_announcement(
            &self,
            request: tonic::Request<super::NodeAnnouncementUpdateRequest>,
        ) -> Result<tonic::Response<super::NodeAnnouncementUpdateResponse>, tonic::Status>;
    }
    #[doc = " Peers is a service that can be used to get information and interact"]
    #[doc = " with the other nodes of the newtwork."]
    #[derive(Debug)]
    pub struct PeersServer<T: Peers> {
        inner: _Inner<T>,
        accept_compression_encodings: (),
        send_compression_encodings: (),
    }
    struct _Inner<T>(Arc<T>);
    impl<T: Peers> PeersServer<T> {
        pub fn new(inner: T) -> Self {
            let inner = Arc::new(inner);
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
            }
        }
        pub fn with_interceptor<F>(inner: T, interceptor: F) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for PeersServer<T>
    where
        T: Peers,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = Never;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/peersrpc.Peers/UpdateNodeAnnouncement" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateNodeAnnouncementSvc<T: Peers>(pub Arc<T>);
                    impl<T: Peers> tonic::server::UnaryService<super::NodeAnnouncementUpdateRequest>
                        for UpdateNodeAnnouncementSvc<T>
                    {
                        type Response = super::NodeAnnouncementUpdateResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::NodeAnnouncementUpdateRequest>,
                        ) -> Self::Future {
                            let inner = self.0.clone();
                            let fut =
                                async move { (*inner).update_node_announcement(request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = UpdateNodeAnnouncementSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec).apply_compression_config(
                            accept_compression_encodings,
                            send_compression_encodings,
                        );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => Box::pin(async move {
                    Ok(http::Response::builder()
                        .status(200)
                        .header("grpc-status", "12")
                        .header("content-type", "application/grpc")
                        .body(empty_body())
                        .unwrap())
                }),
            }
        }
    }
    impl<T: Peers> Clone for PeersServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
            }
        }
    }
    impl<T: Peers> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(self.0.clone())
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: Peers> tonic::transport::NamedService for PeersServer<T> {
        const NAME: &'static str = "peersrpc.Peers";
    }
}
